all: F-1 F-2 F-3


F-1:
	g++ F-1.cpp RentalSystem.cpp RentalContract.cpp Vehicle.cpp Car.cpp SUV.cpp Van.cpp Customer.cpp -o F-1

F-2:
	g++ F-2.cpp RentalSystem.cpp RentalContract.cpp Vehicle.cpp Car.cpp SUV.cpp Van.cpp Customer.cpp -o F-2

F-3:
	g++ F-3.cpp RentalSystem.cpp RentalContract.cpp Vehicle.cpp Car.cpp SUV.cpp Van.cpp Customer.cpp -o F-3


.PHONY: clean F-1 F-2 F-3

clean:
	rm -f ./F-1
	rm -f ./F-2
	rm -f ./F-3