2-1: lec02-1.cpp
	g++ -o 2-1 lec02-1.cpp
2-2: lec02-2.cpp
	g++ -o 2-2 lec02-2.cpp
2-3: lec02-3.cpp
	g++ -o 2-3 lec02-3.cpp
2-4: lec02-4.cpp
	g++ -o 2-4 lec02-4.cpp
2-5: lec02-5.cpp
	g++ -o 2-5 lec02-5.cpp
fptr: fptr.cpp
	g++ -o fptr fptr.cpp
clean:
	rm -f *.o 2-* fptr
