all: A-1 A-2 A-3


A-1:
	g++ A-1.cpp Minecraft.cpp Block.cpp Dirt.cpp Leaf.cpp Rock.cpp Trunk.cpp Player.cpp -o A-1

A-2:
	g++ A-2.cpp Minecraft.cpp Block.cpp Dirt.cpp Leaf.cpp Rock.cpp Trunk.cpp Player.cpp -o A-2

A-3:
	g++ A-3.cpp Minecraft.cpp Block.cpp Dirt.cpp Leaf.cpp Rock.cpp Trunk.cpp Player.cpp -o A-3


.PHONY: clean A-1 A-2 A-3

clean:
	rm -f ./A-1