t1: P1.cpp main.cpp
	g++ -ot1 -DP1T1 P1.cpp main.cpp
t2:	P1.cpp main.cpp
	g++ -ot2 -DP1T2 P1.cpp main.cpp
t3:	P1.cpp main.cpp
	g++ -ot3 -DP1T3 P1.cpp main.cpp
t4:	P1.cpp main.cpp
	g++ -ot4 -DP1T4 P1.cpp main.cpp
clean:
	rm -rf *.o t1 t2 t3 t4
